### ISSUE TITLE
US 07.01.01

### ISSUE THREAD

**Issue by Raffle703** [CMPUT301W23T15/QRHunter#23]
As a player, I want to see game-wide high scores of all players.

**Comment by GemmaryChang** [comment]
done in rankinglist(total score)

**Comment by Eoljjang** [comment]
Nothing showing on screen, do we need to build a new adapter?

**Comment by Eoljjang** [comment]
Leaderboard 1 (rank by total score) created. Still missing Leaderboard 2 (rank by total QR code).

**Comment by GemmaryChang** [comment]
closed
